<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- C# 12: Используем последнюю версию языка для доступа ко всем новым возможностям -->
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\RL-POS.dwg" />
    <None Remove="Resources\RL-POS2.dwg" />
    <None Remove="Resources\Shape_00.png" />
    <None Remove="Resources\Shape_01.png" />
    <None Remove="Resources\Shape_02.png" />
    <None Remove="Resources\Shape_03.png" />
    <None Remove="Resources\Shape_04.png" />
    <None Remove="Resources\Shape_05.png" />
    <None Remove="Resources\Shape_06.png" />
    <None Remove="Resources\Shape_07.png" />
    <None Remove="Resources\Shape_08.png" />
    <None Remove="Resources\Shape_09.png" />
    <None Remove="Resources\Shape_10.png" />
    <None Remove="Resources\Shape_11.png" />
    <None Remove="Resources\Shape_12.png" />
    <None Remove="Resources\Shape_13.png" />
    <None Remove="Resources\Shape_14.png" />
    <None Remove="Resources\Shape_15.png" />
    <None Remove="Resources\Shape_16.png" />
    <None Remove="Resources\Shape_17.png" />
    <None Remove="Resources\Shape_18.png" />
    <None Remove="Resources\Shape_19.png" />
    <None Remove="Resources\Shape_20.png" />
    <None Remove="Resources\Shape_21.png" />
    <None Remove="Resources\Shape_22.png" />
    <None Remove="Resources\Shape_23.png" />
    <None Remove="Resources\Shape_24.png" />
    <None Remove="Resources\Shape_25.png" />
    <None Remove="Resources\Shape_26.png" />
    <None Remove="Resources\Shape_27.png" />
    <None Remove="Resources\Shape_28.png" />
    <None Remove="Resources\Shape_29.png" />
    <None Remove="Resources\Shape_30.png" />
    <None Remove="Resources\Shape_31.png" />
    <None Remove="Resources\Shape_32.png" />
    <None Remove="Resources\Shape_33.png" />
    <None Remove="Resources\Shape_34.png" />
    <None Remove="Resources\Shape_35.png" />
    <None Remove="Resources\Shape_36.png" />
    <None Remove="Resources\Shape_37.png" />
    <None Remove="Resources\Shape_38.png" />
    <None Remove="Resources\Shape_39.png" />
    <None Remove="Resources\Shape_40.png" />
    <None Remove="Resources\Shape_41.png" />
    <None Remove="Resources\Shape_42.png" />
    <None Remove="Resources\Shape_43.png" />
    <None Remove="Resources\Shape_44.png" />
    <None Remove="Resources\Shape_45.png" />
    <None Remove="Resources\Shape_46.png" />
    <None Remove="Resources\Shape_47.png" />
    <None Remove="Resources\Shape_48.png" />
    <None Remove="Resources\Shape_49.png" />
    <None Remove="Resources\Shape_50.png" />
    <None Remove="Resources\Shape_51.png" />
    <None Remove="Resources\Shape_52.png" />
    <None Remove="Resources\Shape_53.png" />
    <None Remove="Resources\Shape_54.png" />
    <None Remove="Resources\Shape_55.png" />
    <None Remove="Resources\Shape_56.png" />
    <None Remove="Resources\Shape_57.png" />
    <None Remove="Resources\Shape_58.png" />
    <None Remove="Resources\Shape_59.png" />
    <None Remove="Resources\Shape_60.png" />
    <None Remove="Resources\Shape_61.png" />
    <None Remove="Resources\Shape_62.png" />
    <None Remove="Resources\Shape_63.png" />
    <None Remove="Resources\Shape_64.png" />
    <None Remove="Resources\Shape_65.png" />
    <None Remove="Resources\Shape_66.png" />
    <None Remove="Resources\Shape_67.png" />
    <None Remove="Resources\Shape_68.png" />
    <None Remove="Resources\Shape_69.png" />
    <None Remove="Resources\Shape_70.png" />
    <None Remove="Resources\Shape_71.png" />
    <None Remove="Resources\Shape_72.png" />
    <None Remove="Resources\Shape_73.png" />
    <None Remove="Resources\Shape_74.png" />
    <None Remove="Resources\Shape_75.png" />
    <None Remove="Resources\Shape_76.png" />
    <None Remove="Resources\Shape_77.png" />
    <None Remove="Resources\Shape_78.png" />
    <None Remove="Resources\Shape_79.png" />
    <None Remove="Resources\Shape_80.png" />
    <None Remove="Resources\Shape_81.png" />
    <None Remove="Resources\Shape_82.png" />
    <None Remove="Resources\Shape_83.png" />
    <None Remove="Resources\Shape_84.png" />
    <None Remove="Resources\Shape_85.png" />
    <None Remove="Resources\Shape_86.png" />
    <None Remove="Resources\Shape_87.png" />
    <None Remove="Resources\Shape_88.png" />
    <None Remove="Resources\Shape_89.png" />
    <None Remove="Resources\Shape_90.png" />
    <None Remove="Resources\Shape_91.png" />
    <None Remove="Resources\Shape_92.png" />
    <None Remove="Resources\Shape_93.png" />
    <!-- Файлы Shape_94.png - Shape_99.png удалены, так как в папке Resources теперь только 94 картинки (00-93) -->
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\RL-POS.dwg" />
    <EmbeddedResource Include="Resources\RL-POS2.dwg" />
  </ItemGroup>

  <!-- AutoCAD 2024: .NET Framework 4.8 -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="AutoCAD.NET" Version="24.3.0" />
    <PackageReference Include="AutoCAD.NET.Core" Version="24.3.0" />
    <PackageReference Include="AutoCAD.NET.Model" Version="24.3.0" />
  </ItemGroup>

  <!-- AutoCAD 2025 + 2026: .NET 8 (25.1.0 is API-compatible with 2026 at runtime) -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="AutoCAD.NET" Version="25.1.0" />
    <PackageReference Include="AutoCAD.NET.Core" Version="25.1.0" />
    <PackageReference Include="AutoCAD.NET.Model" Version="25.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Shape_00.png" />
    <Resource Include="Resources\Shape_01.png" />
    <Resource Include="Resources\Shape_02.png" />
    <Resource Include="Resources\Shape_03.png" />
    <Resource Include="Resources\Shape_04.png" />
    <Resource Include="Resources\Shape_05.png" />
    <Resource Include="Resources\Shape_06.png" />
    <Resource Include="Resources\Shape_07.png" />
    <Resource Include="Resources\Shape_08.png" />
    <Resource Include="Resources\Shape_09.png" />
    <Resource Include="Resources\Shape_10.png" />
    <Resource Include="Resources\Shape_11.png" />
    <Resource Include="Resources\Shape_12.png" />
    <Resource Include="Resources\Shape_13.png" />
    <Resource Include="Resources\Shape_14.png" />
    <Resource Include="Resources\Shape_15.png" />
    <Resource Include="Resources\Shape_16.png" />
    <Resource Include="Resources\Shape_17.png" />
    <Resource Include="Resources\Shape_18.png" />
    <Resource Include="Resources\Shape_19.png" />
    <Resource Include="Resources\Shape_20.png" />
    <Resource Include="Resources\Shape_21.png" />
    <Resource Include="Resources\Shape_22.png" />
    <Resource Include="Resources\Shape_23.png" />
    <Resource Include="Resources\Shape_24.png" />
    <Resource Include="Resources\Shape_25.png" />
    <Resource Include="Resources\Shape_26.png" />
    <Resource Include="Resources\Shape_27.png" />
    <Resource Include="Resources\Shape_28.png" />
    <Resource Include="Resources\Shape_29.png" />
    <Resource Include="Resources\Shape_30.png" />
    <Resource Include="Resources\Shape_31.png" />
    <Resource Include="Resources\Shape_32.png" />
    <Resource Include="Resources\Shape_33.png" />
    <Resource Include="Resources\Shape_34.png" />
    <Resource Include="Resources\Shape_35.png" />
    <Resource Include="Resources\Shape_36.png" />
    <Resource Include="Resources\Shape_37.png" />
    <Resource Include="Resources\Shape_38.png" />
    <Resource Include="Resources\Shape_39.png" />
    <Resource Include="Resources\Shape_40.png" />
    <Resource Include="Resources\Shape_41.png" />
    <Resource Include="Resources\Shape_42.png" />
    <Resource Include="Resources\Shape_43.png" />
    <Resource Include="Resources\Shape_44.png" />
    <Resource Include="Resources\Shape_45.png" />
    <Resource Include="Resources\Shape_46.png" />
    <Resource Include="Resources\Shape_47.png" />
    <Resource Include="Resources\Shape_48.png" />
    <Resource Include="Resources\Shape_49.png" />
    <Resource Include="Resources\Shape_50.png" />
    <Resource Include="Resources\Shape_51.png" />
    <Resource Include="Resources\Shape_52.png" />
    <Resource Include="Resources\Shape_53.png" />
    <Resource Include="Resources\Shape_54.png" />
    <Resource Include="Resources\Shape_55.png" />
    <Resource Include="Resources\Shape_56.png" />
    <Resource Include="Resources\Shape_57.png" />
    <Resource Include="Resources\Shape_58.png" />
    <Resource Include="Resources\Shape_59.png" />
    <Resource Include="Resources\Shape_60.png" />
    <Resource Include="Resources\Shape_61.png" />
    <Resource Include="Resources\Shape_62.png" />
    <Resource Include="Resources\Shape_63.png" />
    <Resource Include="Resources\Shape_64.png" />
    <Resource Include="Resources\Shape_65.png" />
    <Resource Include="Resources\Shape_66.png" />
    <Resource Include="Resources\Shape_67.png" />
    <Resource Include="Resources\Shape_68.png" />
    <Resource Include="Resources\Shape_69.png" />
    <Resource Include="Resources\Shape_70.png" />
    <Resource Include="Resources\Shape_71.png" />
    <Resource Include="Resources\Shape_72.png" />
    <Resource Include="Resources\Shape_73.png" />
    <Resource Include="Resources\Shape_74.png" />
    <Resource Include="Resources\Shape_75.png" />
    <Resource Include="Resources\Shape_76.png" />
    <Resource Include="Resources\Shape_77.png" />
    <Resource Include="Resources\Shape_78.png" />
    <Resource Include="Resources\Shape_79.png" />
    <Resource Include="Resources\Shape_80.png" />
    <Resource Include="Resources\Shape_81.png" />
    <Resource Include="Resources\Shape_82.png" />
    <Resource Include="Resources\Shape_83.png" />
    <Resource Include="Resources\Shape_84.png" />
    <Resource Include="Resources\Shape_85.png" />
    <Resource Include="Resources\Shape_86.png" />
    <Resource Include="Resources\Shape_87.png" />
    <Resource Include="Resources\Shape_88.png" />
    <Resource Include="Resources\Shape_89.png" />
    <Resource Include="Resources\Shape_90.png" />
    <Resource Include="Resources\Shape_91.png" />
    <Resource Include="Resources\Shape_92.png" />
    <Resource Include="Resources\Shape_93.png" />
    <!-- Файлы Shape_94.png - Shape_99.png удалены, так как в папке Resources теперь только 94 картинки (00-93) -->
  </ItemGroup>

</Project>
